name: Build Project
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          check-latest: true

      - name: Compile dataGen
        run: javac -g byteBreak/dataGen.java && mkdir byteBreak/savedata

      - name: Generate data
        run: java byteBreak/dataGen

      - name: Compile project
        run: javac -g **/*.java
